sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creatin an image with dockerfile"
  - docker build -t brisgi/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true brisgi/docker-react npm run test -- --coverage

after_success:
  - ehco "Test success"