sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creatin an image with dockerfile"
  - docker build -t brisgi/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true brisgi/docker-react npm run test -- --coverage

after_success:
  - ehco "Test success"

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-480504116656"
  bucket_path: "docker-react"
  on:
    branch: master

access_key_id: $AWS_ACCESS_ID
secret_access_key: $AWS_ACCESS_KEY